In [23]:
!pip3 install numpy

In [1]:
import numpy as np

In [7]:
arr=np.array([[1,2,3],[5,6,7]])
print(arr)

[[1 2 3]
 [5 6 7]]


In [3]:
arr.ndim

2

In [4]:
arr.shape

(2, 3)

In [5]:
arr.dtype

dtype('int32')

In [11]:
c=np.zeros((3,4))
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
d=np.ones((3,4))
print(d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
f=np.arange(0,30,5)
print(f)

[ 0  5 10 15 20 25]


In [18]:
g=np.linspace(0,5,10)
print(g)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [22]:
v=np.random.random(2)
print(v)

[0.44936079 0.46632378]


In [24]:
new=arr.reshape((3,2))
print(new)

[[1 2]
 [3 5]
 [6 7]]


In [26]:
a=np.array([[2,4,5,6],[6,7,3,4],[8,6,11,2]])
print(a)

[[ 2  4  5  6]
 [ 6  7  3  4]
 [ 8  6 11  2]]


In [27]:
a[:2,::2]

array([[2, 5],
       [6, 3]])

In [33]:
#print ele>0
b=np.array([[-1,2,-3],[4,5,-6]])
print(b)
cond=b>0
temp=b[cond]
print("array of elements > 0: ",temp)

[[-1  2 -3]
 [ 4  5 -6]]
array of elements > 0:  [2 4 5]


In [34]:
#transpose of b
b.T

array([[-1,  4],
       [ 2,  5],
       [-3, -6]])

In [35]:
#max ele row wise
b.max(axis=0)

array([ 4,  5, -3])

In [36]:
#sum of all ele
b.sum()

1

In [39]:
#cumulative sum row wise
b.cumsum()

array([-1,  1, -2,  2,  7,  1], dtype=int32)

In [41]:
print(arr)
print(b)
print("SUM OF 2 MATRIX:")
t=arr+b
print(t)

[[1 2 3]
 [5 6 7]]
[[-1  2 -3]
 [ 4  5 -6]]
SUM OF 2 MATRIX:
[[ 0  4  0]
 [ 9 11  1]]


In [44]:
print(arr)
print(b.T)
print("MUL OF 2 MATRIX:")
m=arr.dot(b.T)
print(m)

[[1 2 3]
 [5 6 7]]
[[-1  4]
 [ 2  5]
 [-3 -6]]
MUL OF 2 MATRIX:
[[ -6  -4]
 [-14   8]]


In [45]:
np.exp(m)

array([[2.47875218e-03, 1.83156389e-02],
       [8.31528719e-07, 2.98095799e+03]])

In [47]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.23606798, 2.44948974, 2.64575131]])

In [52]:
s=np.array([[4,2,3],[5,2,3],[0,5,2]])
print(s)
print("SORTED ARRAY: ")
np.sort(s,axis=1,kind="mergesort")#row wise

[[4 2 3]
 [5 2 3]
 [0 5 2]]
SORTED ARRAY: 


array([[2, 3, 4],
       [2, 3, 5],
       [0, 2, 5]])

In [66]:
print(arr)
print(b)
n=np.vstack((arr,b))
print(n)

[[1 2 3]
 [5 6 7]]
[[-1  2 -3]
 [ 4  5 -6]]
[[ 1  2  3]
 [ 5  6  7]
 [-1  2 -3]
 [ 4  5 -6]]


In [62]:
print(m)
c=[5,6]
np.column_stack((m,c))

[[ -6  -4]
 [-14   8]]


array([[ -6,  -4,   5],
       [-14,   8,   6]])

In [83]:
print(n)
r=np.vsplit(n, 2)
print(r)

[[ 1  2  3]
 [ 5  6  7]
 [-1  2 -3]
 [ 4  5 -6]]
[array([[1, 2, 3],
       [5, 6, 7]]), array([[-1,  2, -3],
       [ 4,  5, -6]])]


In [73]:
print(a)
a.min()

[[ 2  4  5  6]
 [ 6  7  3  4]
 [ 8  6 11  2]]


2

In [74]:
np.median(a)

5.5

In [75]:
np.average(a)

5.333333333333333